version: "3"

services:
  ctf-bot:
    container_name: ctf-bot
    image: ctf-bot
    build:
      context: .
    ports:
      - "8123"
    volumes:
      - ./files:/home/node/files
    restart: unless-stopped
