version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  ctf-bot:
    container_name: ctf-bot
    image: ctf-bot
    build:
      context: .
    ports:
      - "8123"
    volumes:
      - myapp:/home/node/files
    restart: unless-stopped
   
volumes:
  myapp: